const productsData = {
    "wheelchair-18": {
        id: "wheelchair-18",
        name: 'Wheelchair 18" seat, 300lb cap',
        image: "/images/wheelchair-18.jpg",
        features: [
          "Sturdy Frame: Powder-coated silver vein steel frame ensures long-lasting durability.",
          "Easy-to-Clean Upholstery: Embossed vinyl upholstery is lightweight, attractive, and simple to maintain.",
          "Adjustable Seat Height: Dual axle allows seat-to-floor height adjustment from 17.5 inches to 19.5 inches.",
          "Removable Armrests: Available with detachable desk-length armrests for personalized comfort.",
          "Swing-Away Footrests: Equipped with swing-away footrests featuring tool-free adjustable length riggings.",
          "Smooth Mobility: Urethane tires mounted on composite wheels and 8-inch front casters.",
          "Secure Wheel Locks: Push-to-lock wheel locks ensure stability during transfers.",
          "Convenient Storage: Carry pocket on the backrest for personal items.",
        ],
        specifications: [
          { label: "Seat Width", value: "18 inches" },
          { label: "Seat Depth", value: "16 inches" },
          { label: "Seat-to-Floor Height", value: "17.5-19.5 inches" },
          { label: "Back Height", value: "16 inches" },
          { label: "Overall Width (Open)", value: "26 inches" },
          { label: "Overall Width (Closed)", value: "12.5 inches" },
          { label: "Overall Height", value: "36 inches" },
          { label: "Overall Length", value: "42 inches" },
          { label: "Product Weight", value: "41 pounds" },
          { label: "Weight Capacity", value: "300 pounds" },
        ],
      },
    "wheelchair-20": {
      name: 'Wheelchair 20" seat, 300lb cap',
      image: "/images/wheelchair-20.jpg",
      features: [
        "Sturdy Frame: Powder-coated silver vein steel frame ensures long-lasting durability.",
        "Easy-to-Clean Upholstery: Embossed vinyl upholstery is lightweight, attractive, and simple to maintain.",
        "Adjustable Seat Height: Dual axle allows seat-to-floor height adjustment from 17.5 inches to 19.5 inches.",
        "Removable Armrests: Available with detachable desk-length armrests for personalized comfort.",
        "Swing-Away Footrests: Equipped with swing-away footrests.",
        "Smooth Mobility: Urethane tires mounted on composite wheels.",
        "Secure Wheel Locks: Push-to-lock wheel locks for stability.",
      ],
      specifications: [
        { label: "Seat Width", value: "20 inches" },
        { label: "Seat Depth", value: "16 inches" },
        { label: "Seat-to-Floor Height", value: "17.5-19.5 inches" },
        { label: "Back Height", value: "16 inches" },
        { label: "Overall Width (Open)", value: "28 inches" },
        { label: "Overall Width (Closed)", value: "12.5 inches" },
        { label: "Overall Height", value: "36 inches" },
        { label: "Overall Length", value: "42 inches" },
        { label: "Product Weight", value: "42 pounds" },
        { label: "Weight Capacity", value: "300 pounds" },
      ],
    },
    "wheelchair-22": {
      name: "Wheelchair – 22″, 450lbs Capacity",
      image: "/images/wheelchair-22.jpg",
      features: [
        "Heavy-Duty Frame: Constructed with reinforced steel frame featuring dual crossbars.",
        "Enhanced Comfort: Padded, detachable desk-style armrests.",
        "Secure and Safe: Equipped with push-to-lock brakes.",
        "Portable Design: Folds compactly for storage and transportation.",
      ],
      specifications: [
        { label: "Overall Width", value: "29 inches" },
        { label: "Product Weight", value: "57 lbs" },
        { label: "Seat Width", value: "22 inches" },
        { label: "Seat Depth", value: "18 inches" },
        { label: "Weight Capacity", value: "450 lbs" },
        { label: "Frame Material", value: "Steel, black finish" },
        { label: "Wheel Diameter", value: "22 inches" },
        { label: "Front Caster Diameter", value: "8 inches" },
      ],
    },
    "elevating-leg-rest": {
      name: "Elevating Leg Rest",
      image: "/images/leg-rest.jpg",
      features: [
        "High-Quality Design: Aluminum footplates are lightweight yet sturdy.",
        "Padded Calf Pads: Soft padding provides superior support.",
        "Customizable Comfort: Adjustable design for optimal positioning.",
      ],
      specifications: [
        { label: "Material", value: "Aluminum footplates" },
        { label: "Padding", value: "Cushioned calf pads" },
        { label: "Weight", value: "Lightweight" },
        { label: "Included Items", value: "One pair of elevating leg rests" },
      ],
    },
    "transport-chair": {
      name: 'Transport Chair, 19" seat, 300lbs capacity',
      image: "/images/transport-chair.jpg",
      features: [
        "Lightweight and Compact: Only 18 lbs for easy maneuverability.",
        'Comfortable Seating: 19" seat width with padded fixed armrests.',
        "Convenient Footrests: Swing-away footrests included.",
        "Easy Storage: Foldable back for compact storage.",
      ],
      specifications: [
        { label: "Seat Dimensions", value: '19" width, 16" depth' },
        { label: "Seat-to-Floor Height", value: "19″" },
        { label: "Weight Capacity", value: "300 lbs" },
        { label: "Product Weight", value: "18 lbs" },
        { label: "Overall Width", value: "23.5″" },
        { label: "Folded Width", value: "10.75″" },
      ],
    },
    "homecare-bed-foam": {
      name: "Full Electric Homecare Bed (rails & foam mattress)",
      image: "/images/homecare-bed-foam.jpg",
      features: [
        "Durable 2-piece tubular frame for reinforced strength.",
        "Four 3-inch castors with two locking and two swivel.",
        "Washable and long-lasting bed ends.",
        "Mattress retainer system included.",
        "Available with full or half side rails.",
      ],
      specifications: [
        { label: "Height Range", value: "15 in – 23 in" },
        { label: "Bed Length", value: "86 in" },
        { label: "Width", value: "36 in" },
        { label: "Weight", value: "165 lb" },
        { label: "Weight Capacity", value: "450 lb" },
      ],
    },
    "homecare-bed-ltc": {
      name: "Full Electric Homecare Bed (rails & LTC mattress)",
      image: "/images/homecare-bed-ltc.jpg",
      features: [
        "Durable 2-piece tubular frame.",
        "Four 3-inch castors with locking mechanism.",
        "Premium LTC mattress for enhanced comfort.",
        "Mattress retainer system.",
        "Choice of full or half side rails.",
      ],
      specifications: [
        { label: "Height Range", value: "15 in – 23 in" },
        { label: "Maximum Back Angle", value: "70°" },
        { label: "Maximum Knee Angle", value: "45°" },
        { label: "Weight Capacity", value: "450 lb" },
      ],
    },
    "trapeze-bar-attachment": {
      name: "Trapeze Bar Attachment (for Home Care Beds)",
      image: "/images/trapeze-attachment.jpg",
      features: [
        '34" Reach for easy repositioning.',
        "Chrome Frame for durability.",
        "Complete Bracket Set included.",
        "Heavy-Gauge Steel Construction.",
        "Nylon-Coated Hand Bar for secure grip.",
      ],
      specifications: [{ label: "Weight Capacity", value: "250 lbs" }],
    },
    "trapeze-bar-base": {
      name: "Trapeze Bar with Base (for regular beds)",
      image: "/images/trapeze-base.jpg",
      features: [
        "Wide Range of Adjustability.",
        "Heavy-Gauge Steel Construction.",
        "Nylon-Coated Hand Bar.",
        "Protective Wall Bumpers.",
      ],
      specifications: [
        { label: "Overall Height", value: "61 in" },
        { label: "Reach", value: "34 in" },
        { label: "Weight Capacity", value: "250 lbs" },
      ],
    },
    "patient-lift": {
      name: "Patient Lift, Manual (sling sold separately)",
      image: "/images/patient-lift.jpg",
      features: [
        "Durable Steel Construction with Silver Vein finish.",
        "6-Point Swivel Bar for 2 or 4 sling straps.",
        "Smooth Hydraulic Operation.",
        "Adjustable Base Width.",
        "Choice of 3″ or 5″ casters.",
      ],
      specifications: [
        { label: "Weight Capacity", value: "450 lbs" },
        { label: "Boom Height", value: "17.5″ – 72″" },
        { label: "Weight", value: "72 lbs" },
        { label: "Casters", value: "5″" },
      ],
    },
    "overbed-table": {
      name: "Over Bed Tables",
      image: "/images/overbed-table.jpg",
      features: [
        'Height adjustable from 30" – 43".',
        "Walnut wood grain laminate top.",
        "Locking swivel wheels.",
        "Heavy-gauge steel construction.",
      ],
      specifications: [
        { label: "Overall Width", value: "30 inches" },
        { label: "Dimensions High", value: "29w x 15.5d x 42.75h" },
        { label: "Dimensions Low", value: "29w x 15.5d x 29.75h" },
        { label: "Material Frame", value: "STEEL" },
      ],
    },
    "knee-walker": {
      name: 'Knee Walker, 8" wheels & basket',
      image: "/images/knee-walker.jpg",
      features: [
        "Height Adjustable for various users.",
        "Dual Handbrakes for safety.",
        "8-Inch Wheels for smooth movement.",
        "Foldable Handlebar.",
        "Comfortable Knee Pad.",
        "Convenient Storage Basket.",
      ],
      specifications: [
        { label: "Weight Capacity", value: "300 pounds" },
        { label: "Product Weight", value: "21 pounds" },
        { label: "Handle Height Range", value: "31 to 41 inches" },
        { label: "Knee Pad Height Range", value: "16.5 to 20.5 inches" },
      ],
    },
    "wheelchair-16": {
      name: "Wheelchair 16″ Seat, 300lbs capacity",
      image: "/images/wheelchair-16.jpg",
      features: [
        "Height Adjustable between hemi and standard heights.",
        "Dual Handbrakes for superior control.",
        "Fixed footrests for stability.",
        "Push-to-lock braking system.",
      ],
      specifications: [
        { label: "Seat Dimensions", value: '16" W x 16" D' },
        { label: "Seat-to-Floor Height", value: '17.5" - 19.5"' },
        { label: "Back Height", value: '19"' },
        { label: "Width Between Arms", value: '16.5"' },
        { label: "Overall Width", value: '24"' },
        { label: "Weight Capacity", value: "300 lbs" },
      ],
    },
  }
  
  export default productsData
  
  